#!/bin/bash

convert AppIcon.png -resize 58x58 AppIcon29x29@2x.png
convert AppIcon.png -resize 87x87 AppIcon29x29@3x.png

convert AppIcon.png -resize 80x80 AppIcon40x40@2x.png
convert AppIcon.png -resize 120x120 AppIcon40x40@3x.png

convert AppIcon.png -resize 120x120 AppIcon60x60@2x.png
convert AppIcon.png -resize 180x180 AppIcon60x60@3x.png

convert AppIcon.png -resize 29x29 AppIcon29x29@1x.png
convert AppIcon.png -resize 58x58 AppIcon29x29@2x-1.png

convert AppIcon.png -resize 40x40 AppIcon40x40@1x.png
convert AppIcon.png -resize 80x80 AppIcon40x40@2x-1.png

convert AppIcon.png -resize 76x76 AppIcon76x76@1x.png
convert AppIcon.png -resize 152x152 AppIcon76x76@2x.png

convert AppIcon.png -resize 167x167 AppIcon83.5x83.5@2x.png

convert AppIcon.png -resize 1024x1024 iTunesArtwork@2x.png

